---
apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
spec:
  logLevel: debug
  #nodeSelector:
  #  node-role.kubernetes.io/worker: ""
  #speakerTolerations:
  #  - key: "Example"
  #    operator: "Exists"
  #    effect: "NoExecute"
  #controllerConfig:
  #  runtimeClassName: myclass
  #  annotations: 
  #    controller: demo
  #  resources:
  #    limits:
  #      cpu: "200m"
  #  priorityClassName: high-priority
  #  affinity:
  #    podAffinity:
  #      requiredDuringSchedulingIgnoredDuringExecution:
  #      - labelSelector:
  #          matchLabels:
  #            app: metallb
  #        topologyKey: kubernetes.io/hostname
  #
  #speakerConfig:
  #  runtimeClassName: myclass
  #  annotations: 
  #    speaker: demo
  #  resources:
  #    limits:
  #      cpu: "200m"
  #  priorityClassName: high-priority
  #  affinity:
  #    podAffinity:
  #      requiredDuringSchedulingIgnoredDuringExecution:
  #      - labelSelector:
  #          matchLabels:
  #            app: metallb
  #        topologyKey: kubernetes.io/hostname