---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workload-test

resources:
  - cluster-issuer-letsencrypt.yml
  - namespace.yml
  - deployment.yml
  - service.yml
  - ingress.yml
