---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: cert-manager-operator

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable-v1.11'
    target:
      kind: Subscription
      name: openshift-cert-manager-operator